/**
 * Copyright (c) 2016 DFKI GmbH
 *
 * Author: Felix Wenk <felix.wenk@dfki.de>
 */
#ifndef __IMU_ACCUMULATE_H
#define __IMU_ACCUMULATE_H

#include <list>
#include <Eigen/Dense>

namespace LIR {

    /** Entry in an IMU accumulate series. An IMUAccumulateEntry contains the
     * accumulated information combined with the angular velocity of the moment
     * of the last modification of the accumulte. This is the information normally
     * sent by an IMU to a sensor fusion unit. */
    struct IMUAccumulateEntry
    {
        unsigned int usecs;
        Eigen::Quaterniond orientation;
        Eigen::Vector3d velocity;
        Eigen::Vector3d angular_velocity;
    };

    /** IMUAccumulates contains a time-series of accumulates generated by an IMU. */
    class IMUAccumulates
    {
    public:
        std::list<IMUAccumulateEntry> entries;
        /** Constructor reading the accumulates from the file with the given name. */
        IMUAccumulates(const std::string& filename);
    };
}

#endif // __IMU_ACCUMULATE_H
